version: '3'
services:
  db:
    image: mysql:latest
    volumes:
      - pai-sql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: pai
      MYSQL_PASSWORD: tigers
      MYSQL_DATABASE: pai_review_dev
      TZ: "Asia/Tokyo"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/pai-review
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  pai-sql:
