default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: pai
  password: tigers
  host: db

development:
  <<: *default
  database: pai_review_dev

test:
  <<: *default
  database: pai_review_test

production:
  <<: *default
  database: <%= ENV['PAI_REVIEW_DATABASE'] %>
  host: <%= ENV['PAI_REVIEW_HOST'] %>
  username: <%= ENV['PAI_REVIEW_USERNAME'] %>
  password: <%= ENV['PAI_REVIEW_PASSWORD'] %>
